language: node_js
node_js:
- '6'
- '5'
sudo: required
dist: trusty
install:
- npm install
script:
- npm test
after_script:
- node --harmony_proxies node_modules/.bin/jest --coverage && cat ./coverage/lcov.info
  | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - master
  - gh-pages
env:
  global:
    secure: jhYIQ5m+ZZc8sw8ecZxsXBLvGUMqkqvnFVW6tlGNhH2W5rvOFPZnfnVGVYOoAzBv2uZQIlLMcrJj8a78XjUWrTvQueDJ5YjCkKevJwz+7llchPN77Ue5yb0EbAtU9NT8n2oIisBmg4+/gJ+vntmqmJuaLQEUQm7sHdDT22IXAPqZNlrFWoz/Na1+AYr/IKF78GARudzPS9ITVsJA+wYyv3Uw7utyv9zn5b6zsf//eLUQoa9ndNXQnnTvrWm73rOOOmx40Zr0OUWeH6qFCtAO67qky5ZEyLNqzUDWp62/Isu/Td7XueDPQqe1dWjDJ9PS6aX2EIxBpvFanZnX3wtARjKPK0aGPH1ZYBwmbgHgLQ5pIm5+lH4LanfsKfXNnjmmMfoBfDqRB8IO0ODEhu/ZQv7oyn7FhPbyYvcDbn0g+CoMCuOKTMxsQc+v705HfD9Q1ryogoZszY8KntBsf1fKEF+eBCzqsv6ZsPOQkh93mbtJFo5RDLYeo1PiOBwrThjn6WaLhIs7lmp3EJMUMgsyJLFmHPkwAf3slhWuau9eBYPLVLXBSaFnPpuLSes/58yFWxJcRsFBJuj4LGFhIe8vXE/kj4fmzwbVdWwiqO7QJR/C4fdHDiOH6Kf9VLiXTGHipRWDI5NWZNGDGjkN01/CCIi8kHwnr3nm1SV1xR3u460=
